### ISSUE TITLE
Mapping alarm definition to notification

### ISSUE THREAD

**Issue by mehuljn** [stackhpc/monasca-grafana-app#20]
We have create a "notification" via the notification UI. We have also created a "alarm-definition" but we don't find any place where we can map the alarm definition to a notification in Grafana Plugin.

Request you to please provide some assistance and understanding

**Comment by dougszumski** [comment]
That's correct @mehuljn. @Charana123 has fixed this issue here: https://github.com/monasca/monasca-grafana  Please try the master branch from there, and file any issues you find in that repo. We are migrating this repo to the monasca github repo. Thanks.
