### ISSUE TITLE
Alarm Definitions: Click on name -> "App Page Not Found"

### ISSUE THREAD

**Issue by mattibf** [stackhpc/monasca-grafana-app#6]
I do the following
- Monasca -> Alarm Definitions
- Click on name of one Alarm Definition
Observed behavior: A new page is displayed, with a red box: "App Page Not Found"
Expected behavior: The page to edit the alarm definition is shown.
Note: Click on the symbol to edit the alarm definition is working.

**Comment by dougszumski** [comment]
Thanks for reporting this. I've confirmed that I can reproduce the issue.

**Comment by dougszumski** [comment]
@Charana123 has fixed this.
