### ISSUE TITLE
Edit Alarm Definition, click "Save": Hangs forever

### ISSUE THREAD

**Issue by mattibf** [stackhpc/monasca-grafana-app#7]
I do the following
- Monasca -> Alarm Definitions
- Click on edit button for one alarm definition
- Apply some change
- Click Save
Expected behavior: After some time, the save returns with a msg "successfully updated or similar.
Observed behavior: Save is pending forever.
Note: The alarm defintion has been updated in the database.
It's displayed with the correct, changed values

**Comment by dougszumski** [comment]
Thanks for reporting this as well! I confirm that I can also reproduce this issue.

**Comment by dougszumski** [comment]
@Charana123 has fixed this.
